# Generated by Django 5.2.4 on 2025-07-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Descriere')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preț')),
                ('condition', models.CharField(choices=[('new', 'Nou'), ('very_good', 'Foarte bună'), ('good', 'Bună'), ('satisfactory', 'Satisfăcătoare'), ('for_parts', 'Pentru piese')], max_length=20, verbose_name='Stare')),
                ('city', models.CharField(max_length=100, verbose_name='Oraș')),
                ('county', models.CharField(max_length=100, verbose_name='Județ')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('sold', 'Vândut'), ('expired', 'Expirat'), ('draft', 'Ciornă')], default='active', max_length=20, verbose_name='Status')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='Preț negociabil')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vizualizări')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiră la')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Categorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Proprietar')),
            ],
            options={
                'verbose_name': 'Anunț',
                'verbose_name_plural': 'Anunțuri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/%d/', verbose_name='Imagine')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Text alternativ')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagine principală')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Imagine anunț',
                'verbose_name_plural': 'Imagini anunțuri',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='Salvat la')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing', verbose_name='Anunț')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Anunț salvat',
                'verbose_name_plural': 'Anunțuri salvate',
                'unique_together': {('user', 'listing')},
            },
        ),
    ]
