# Generated by Django 5.2.4 on 2025-07-20 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Oraș')),
                ('county', models.CharField(blank=True, max_length=100, verbose_name='Județ')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Despre mine')),
                ('total_listings', models.PositiveIntegerField(default=0, verbose_name='Total anunțuri')),
                ('total_sold', models.PositiveIntegerField(default=0, verbose_name='Total vândute')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notificări email')),
                ('phone_public', models.BooleanField(default=True, verbose_name='Telefon public')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilizator',
                'verbose_name_plural': 'Profiluri utilizatori',
            },
        ),
    ]
